//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 01:10:56 PM AEST 
//


package com.anz.CobolHelloWorldAPI.transform.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PurchaseData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PurchaseData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemCount">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Comp__short">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="99"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CustomerInitial" maxOccurs="2" minOccurs="2">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Invoice">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Item" maxOccurs="50">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ItemType">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                                   &lt;maxLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;choice>
 *                               &lt;element name="ItemGrocery">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="ItemCode">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                                               &lt;maxLength value="10"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                         &lt;element name="Description">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                                               &lt;maxLength value="30"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                         &lt;element name="Price">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__decimal">
 *                                               &lt;minInclusive value="0"/>
 *                                               &lt;maxInclusive value="9999.99"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                         &lt;element name="SellByDate">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
 *                                               &lt;minInclusive value="0"/>
 *                                               &lt;maxInclusive value="99999999"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                         &lt;element name="Quantity">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
 *                                               &lt;minInclusive value="0"/>
 *                                               &lt;maxInclusive value="999999"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="ItemNonGrocery">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="ItemCode">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                                               &lt;maxLength value="10"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                         &lt;element name="Description">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                                               &lt;maxLength value="30"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                         &lt;element name="Price">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__decimal">
 *                                               &lt;minInclusive value="0"/>
 *                                               &lt;maxInclusive value="9999.99"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                         &lt;element name="Colour">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                                               &lt;maxLength value="8"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                         &lt;element name="Quantity">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
 *                                               &lt;minInclusive value="0"/>
 *                                               &lt;maxInclusive value="999999"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/choice>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchaseData", propOrder = {
    "itemCount",
    "customerInitial",
    "text",
    "invoice"
})
public class PurchaseData {

    @XmlElement(name = "ItemCount", defaultValue = "0")
    protected int itemCount;
    @XmlElement(name = "CustomerInitial", required = true, defaultValue = " ")
    protected List<String> customerInitial;
    @XmlElement(name = "text", required = true, defaultValue = " ")
    protected String text;
    @XmlElement(name = "Invoice", required = true)
    protected PurchaseData.Invoice invoice;

    /**
     * Gets the value of the itemCount property.
     * 
     */
    public int getItemCount() {
        return itemCount;
    }

    /**
     * Sets the value of the itemCount property.
     * 
     */
    public void setItemCount(int value) {
        this.itemCount = value;
    }

    /**
     * Gets the value of the customerInitial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customerInitial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomerInitial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCustomerInitial() {
        if (customerInitial == null) {
            customerInitial = new ArrayList<String>();
        }
        return this.customerInitial;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the invoice property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaseData.Invoice }
     *     
     */
    public PurchaseData.Invoice getInvoice() {
        return invoice;
    }

    /**
     * Sets the value of the invoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaseData.Invoice }
     *     
     */
    public void setInvoice(PurchaseData.Invoice value) {
        this.invoice = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Item" maxOccurs="50">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ItemType">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *                         &lt;maxLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;choice>
     *                     &lt;element name="ItemGrocery">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="ItemCode">
     *                                 &lt;simpleType>
     *                                   &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *                                     &lt;maxLength value="10"/>
     *                                   &lt;/restriction>
     *                                 &lt;/simpleType>
     *                               &lt;/element>
     *                               &lt;element name="Description">
     *                                 &lt;simpleType>
     *                                   &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *                                     &lt;maxLength value="30"/>
     *                                   &lt;/restriction>
     *                                 &lt;/simpleType>
     *                               &lt;/element>
     *                               &lt;element name="Price">
     *                                 &lt;simpleType>
     *                                   &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__decimal">
     *                                     &lt;minInclusive value="0"/>
     *                                     &lt;maxInclusive value="9999.99"/>
     *                                   &lt;/restriction>
     *                                 &lt;/simpleType>
     *                               &lt;/element>
     *                               &lt;element name="SellByDate">
     *                                 &lt;simpleType>
     *                                   &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
     *                                     &lt;minInclusive value="0"/>
     *                                     &lt;maxInclusive value="99999999"/>
     *                                   &lt;/restriction>
     *                                 &lt;/simpleType>
     *                               &lt;/element>
     *                               &lt;element name="Quantity">
     *                                 &lt;simpleType>
     *                                   &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
     *                                     &lt;minInclusive value="0"/>
     *                                     &lt;maxInclusive value="999999"/>
     *                                   &lt;/restriction>
     *                                 &lt;/simpleType>
     *                               &lt;/element>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="ItemNonGrocery">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="ItemCode">
     *                                 &lt;simpleType>
     *                                   &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *                                     &lt;maxLength value="10"/>
     *                                   &lt;/restriction>
     *                                 &lt;/simpleType>
     *                               &lt;/element>
     *                               &lt;element name="Description">
     *                                 &lt;simpleType>
     *                                   &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *                                     &lt;maxLength value="30"/>
     *                                   &lt;/restriction>
     *                                 &lt;/simpleType>
     *                               &lt;/element>
     *                               &lt;element name="Price">
     *                                 &lt;simpleType>
     *                                   &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__decimal">
     *                                     &lt;minInclusive value="0"/>
     *                                     &lt;maxInclusive value="9999.99"/>
     *                                   &lt;/restriction>
     *                                 &lt;/simpleType>
     *                               &lt;/element>
     *                               &lt;element name="Colour">
     *                                 &lt;simpleType>
     *                                   &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *                                     &lt;maxLength value="8"/>
     *                                   &lt;/restriction>
     *                                 &lt;/simpleType>
     *                               &lt;/element>
     *                               &lt;element name="Quantity">
     *                                 &lt;simpleType>
     *                                   &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
     *                                     &lt;minInclusive value="0"/>
     *                                     &lt;maxInclusive value="999999"/>
     *                                   &lt;/restriction>
     *                                 &lt;/simpleType>
     *                               &lt;/element>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/choice>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class Invoice {

        @XmlElement(name = "Item", required = true)
        protected List<PurchaseData.Invoice.Item> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PurchaseData.Invoice.Item }
         * 
         * 
         */
        public List<PurchaseData.Invoice.Item> getItem() {
            if (item == null) {
                item = new ArrayList<PurchaseData.Invoice.Item>();
            }
            return this.item;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ItemType">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
         *               &lt;maxLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;choice>
         *           &lt;element name="ItemGrocery">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;sequence>
         *                     &lt;element name="ItemCode">
         *                       &lt;simpleType>
         *                         &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
         *                           &lt;maxLength value="10"/>
         *                         &lt;/restriction>
         *                       &lt;/simpleType>
         *                     &lt;/element>
         *                     &lt;element name="Description">
         *                       &lt;simpleType>
         *                         &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
         *                           &lt;maxLength value="30"/>
         *                         &lt;/restriction>
         *                       &lt;/simpleType>
         *                     &lt;/element>
         *                     &lt;element name="Price">
         *                       &lt;simpleType>
         *                         &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__decimal">
         *                           &lt;minInclusive value="0"/>
         *                           &lt;maxInclusive value="9999.99"/>
         *                         &lt;/restriction>
         *                       &lt;/simpleType>
         *                     &lt;/element>
         *                     &lt;element name="SellByDate">
         *                       &lt;simpleType>
         *                         &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
         *                           &lt;minInclusive value="0"/>
         *                           &lt;maxInclusive value="99999999"/>
         *                         &lt;/restriction>
         *                       &lt;/simpleType>
         *                     &lt;/element>
         *                     &lt;element name="Quantity">
         *                       &lt;simpleType>
         *                         &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
         *                           &lt;minInclusive value="0"/>
         *                           &lt;maxInclusive value="999999"/>
         *                         &lt;/restriction>
         *                       &lt;/simpleType>
         *                     &lt;/element>
         *                   &lt;/sequence>
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *           &lt;element name="ItemNonGrocery">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;sequence>
         *                     &lt;element name="ItemCode">
         *                       &lt;simpleType>
         *                         &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
         *                           &lt;maxLength value="10"/>
         *                         &lt;/restriction>
         *                       &lt;/simpleType>
         *                     &lt;/element>
         *                     &lt;element name="Description">
         *                       &lt;simpleType>
         *                         &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
         *                           &lt;maxLength value="30"/>
         *                         &lt;/restriction>
         *                       &lt;/simpleType>
         *                     &lt;/element>
         *                     &lt;element name="Price">
         *                       &lt;simpleType>
         *                         &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__decimal">
         *                           &lt;minInclusive value="0"/>
         *                           &lt;maxInclusive value="9999.99"/>
         *                         &lt;/restriction>
         *                       &lt;/simpleType>
         *                     &lt;/element>
         *                     &lt;element name="Colour">
         *                       &lt;simpleType>
         *                         &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
         *                           &lt;maxLength value="8"/>
         *                         &lt;/restriction>
         *                       &lt;/simpleType>
         *                     &lt;/element>
         *                     &lt;element name="Quantity">
         *                       &lt;simpleType>
         *                         &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
         *                           &lt;minInclusive value="0"/>
         *                           &lt;maxInclusive value="999999"/>
         *                         &lt;/restriction>
         *                       &lt;/simpleType>
         *                     &lt;/element>
         *                   &lt;/sequence>
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *         &lt;/choice>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "itemType",
            "itemGrocery",
            "itemNonGrocery"
        })
        public static class Item {

            @XmlElement(name = "ItemType", required = true, defaultValue = " ")
            protected String itemType;
            @XmlElement(name = "ItemGrocery")
            protected PurchaseData.Invoice.Item.ItemGrocery itemGrocery;
            @XmlElement(name = "ItemNonGrocery")
            protected PurchaseData.Invoice.Item.ItemNonGrocery itemNonGrocery;

            /**
             * Gets the value of the itemType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getItemType() {
                return itemType;
            }

            /**
             * Sets the value of the itemType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setItemType(String value) {
                this.itemType = value;
            }

            /**
             * Gets the value of the itemGrocery property.
             * 
             * @return
             *     possible object is
             *     {@link PurchaseData.Invoice.Item.ItemGrocery }
             *     
             */
            public PurchaseData.Invoice.Item.ItemGrocery getItemGrocery() {
                return itemGrocery;
            }

            /**
             * Sets the value of the itemGrocery property.
             * 
             * @param value
             *     allowed object is
             *     {@link PurchaseData.Invoice.Item.ItemGrocery }
             *     
             */
            public void setItemGrocery(PurchaseData.Invoice.Item.ItemGrocery value) {
                this.itemGrocery = value;
            }

            /**
             * Gets the value of the itemNonGrocery property.
             * 
             * @return
             *     possible object is
             *     {@link PurchaseData.Invoice.Item.ItemNonGrocery }
             *     
             */
            public PurchaseData.Invoice.Item.ItemNonGrocery getItemNonGrocery() {
                return itemNonGrocery;
            }

            /**
             * Sets the value of the itemNonGrocery property.
             * 
             * @param value
             *     allowed object is
             *     {@link PurchaseData.Invoice.Item.ItemNonGrocery }
             *     
             */
            public void setItemNonGrocery(PurchaseData.Invoice.Item.ItemNonGrocery value) {
                this.itemNonGrocery = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ItemCode">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
             *               &lt;maxLength value="10"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Description">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
             *               &lt;maxLength value="30"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Price">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__decimal">
             *               &lt;minInclusive value="0"/>
             *               &lt;maxInclusive value="9999.99"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="SellByDate">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
             *               &lt;minInclusive value="0"/>
             *               &lt;maxInclusive value="99999999"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Quantity">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
             *               &lt;minInclusive value="0"/>
             *               &lt;maxInclusive value="999999"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "itemCode",
                "description",
                "price",
                "sellByDate",
                "quantity"
            })
            public static class ItemGrocery {

                @XmlElement(name = "ItemCode", required = true, defaultValue = " ")
                protected String itemCode;
                @XmlElement(name = "Description", required = true, defaultValue = " ")
                protected String description;
                @XmlElement(name = "Price", required = true, defaultValue = "0")
                protected BigDecimal price;
                @XmlElement(name = "SellByDate", defaultValue = "0")
                protected long sellByDate;
                @XmlElement(name = "Quantity", defaultValue = "0")
                protected long quantity;

                /**
                 * Gets the value of the itemCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getItemCode() {
                    return itemCode;
                }

                /**
                 * Sets the value of the itemCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setItemCode(String value) {
                    this.itemCode = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the price property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getPrice() {
                    return price;
                }

                /**
                 * Sets the value of the price property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setPrice(BigDecimal value) {
                    this.price = value;
                }

                /**
                 * Gets the value of the sellByDate property.
                 * 
                 */
                public long getSellByDate() {
                    return sellByDate;
                }

                /**
                 * Sets the value of the sellByDate property.
                 * 
                 */
                public void setSellByDate(long value) {
                    this.sellByDate = value;
                }

                /**
                 * Gets the value of the quantity property.
                 * 
                 */
                public long getQuantity() {
                    return quantity;
                }

                /**
                 * Sets the value of the quantity property.
                 * 
                 */
                public void setQuantity(long value) {
                    this.quantity = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ItemCode">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
             *               &lt;maxLength value="10"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Description">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
             *               &lt;maxLength value="30"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Price">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__decimal">
             *               &lt;minInclusive value="0"/>
             *               &lt;maxInclusive value="9999.99"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Colour">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
             *               &lt;maxLength value="8"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Quantity">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
             *               &lt;minInclusive value="0"/>
             *               &lt;maxInclusive value="999999"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "itemCode",
                "description",
                "price",
                "colour",
                "quantity"
            })
            public static class ItemNonGrocery {

                @XmlElement(name = "ItemCode", required = true, defaultValue = "          ")
                protected String itemCode;
                @XmlElement(name = "Description", required = true, defaultValue = "                              ")
                protected String description;
                @XmlElement(name = "Price", required = true, defaultValue = "0")
                protected BigDecimal price;
                @XmlElement(name = "Colour", required = true, defaultValue = "        ")
                protected String colour;
                @XmlElement(name = "Quantity", defaultValue = "0")
                protected long quantity;

                /**
                 * Gets the value of the itemCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getItemCode() {
                    return itemCode;
                }

                /**
                 * Sets the value of the itemCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setItemCode(String value) {
                    this.itemCode = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the price property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getPrice() {
                    return price;
                }

                /**
                 * Sets the value of the price property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setPrice(BigDecimal value) {
                    this.price = value;
                }

                /**
                 * Gets the value of the colour property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getColour() {
                    return colour;
                }

                /**
                 * Sets the value of the colour property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setColour(String value) {
                    this.colour = value;
                }

                /**
                 * Gets the value of the quantity property.
                 * 
                 */
                public long getQuantity() {
                    return quantity;
                }

                /**
                 * Sets the value of the quantity property.
                 * 
                 */
                public void setQuantity(long value) {
                    this.quantity = value;
                }

            }

        }

    }

}
